package Interface;
package logik;


import java.awt.Color;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import logik.DataManager;
import logik.LearningManager;
import logik.MySQLAccess;
import logik.Verb;
import logik.Vokabel;


/**
 *
 * @author Raphael Möller
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() throws Exception {
        initComponents();
        updateUebersicht();
        initUhr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        pnlMain = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        pnlSidebarUebersicht = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlSidebarLernen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlVokabeln = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlKana = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlKanji = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlSidebarKatalog = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlHinzufuegen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBearbeiten = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlSidebarEinstellungen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlSidebarVerlassen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlContentUebersicht = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txfUebersichtSehrGut = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txfUebersichtAnzahlWoerter = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txfUebersichtGut = new javax.swing.JTextField();
        txfUebersichtSchlecht = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        pnlContentStart = new javax.swing.JPanel();
        txfStartUser = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlStartAnmelden = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        pnlContentVokabeln = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlContentKana = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txfKanaContentPunkteFalsch = new javax.swing.JTextField();
        txfKanaContentPunkteRichtig = new javax.swing.JTextField();
        pnlKanaContent = new javax.swing.JPanel();
        pnlKanaContentSeite1 = new javax.swing.JPanel();
        ckbxKanaContentSeite1btn3 = new javax.swing.JCheckBox();
        ckbxKanaContentSeite1btn5 = new javax.swing.JCheckBox();
        ckbxKanaContentSeite1btn2 = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        ckbxKanaContentSeite1btn1 = new javax.swing.JCheckBox();
        ckbxKanaContentSeite1btn4 = new javax.swing.JCheckBox();
        pnlKanaContentSeite1Start = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        pnlKanaContentSeite2 = new javax.swing.JPanel();
        txfKanaContentSeite2Vorgabe = new javax.swing.JTextField();
        txfKanaContentSeite2Antwort1 = new javax.swing.JTextField();
        txfKanaContentSeite2Antwort2 = new javax.swing.JTextField();
        txfKanaContentSeite2Antwort3 = new javax.swing.JTextField();
        pnlKanaContentSeite3 = new javax.swing.JPanel();
        txfKanaContentSeite3Vorgabe = new javax.swing.JTextField();
        txfKanaContentSeite3Antwort = new javax.swing.JTextField();
        pnlKanaContentSeite4 = new javax.swing.JPanel();
        pnlContentKanji = new javax.swing.JPanel();
        pnlContentKatalog = new javax.swing.JPanel();
        pnlContentHinzufuegen = new javax.swing.JPanel();
        txfNeuesWortJ = new javax.swing.JTextField();
        txfNeuesWortD = new javax.swing.JTextField();
        cbxNeuesWortKat1 = new javax.swing.JComboBox<>();
        cbxNeuesWortKat2 = new javax.swing.JComboBox<>();
        cbxNeuesWortKat3 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblUebersetzung = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        pnlNeuesWortHinzufuegen = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlNeuesWortVerbformen = new javax.swing.JPanel();
        txfNeuesWortVerbform1 = new javax.swing.JTextField();
        txfNeuesWortVerbform2 = new javax.swing.JTextField();
        txfNeuesWortVerbform3 = new javax.swing.JTextField();
        txfNeuesWortVerbform4 = new javax.swing.JTextField();
        txfNeuesWortVerbform5 = new javax.swing.JTextField();
        txfNeuesWortVerbform6 = new javax.swing.JTextField();
        txfNeuesWortVerbform7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        pnlContentEinstellungen = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        txfMainUhr = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vocs");
        setLocation(new java.awt.Point(-10, 0));
        setName("Vocs"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(11, 15, 30));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMainMouseEntered(evt);
            }
        });
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidebar.setBackground(new java.awt.Color(23, 23, 56));
        pnlSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidebarUebersicht.setBackground(new java.awt.Color(46, 23, 96));
        pnlSidebarUebersicht.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSidebarUebersichtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSidebarUebersichtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSidebarUebersichtMouseExited(evt);
            }
        });
        pnlSidebarUebersicht.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 243, 228));
        jLabel2.setText("Übersicht");
        pnlSidebarUebersicht.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebar.add(pnlSidebarUebersicht, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        pnlSidebarLernen.setBackground(new java.awt.Color(55, 28, 115));
        pnlSidebarLernen.setEnabled(false);
        pnlSidebarLernen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSidebarLernenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSidebarLernenMouseExited(evt);
            }
        });
        pnlSidebarLernen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 243, 228));
        jLabel3.setText("Lernen");
        pnlSidebarLernen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlVokabeln.setBackground(new java.awt.Color(55, 43, 135));
        pnlVokabeln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlVokabelnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlVokabelnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlVokabelnMouseExited(evt);
            }
        });
        pnlVokabeln.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 243, 228));
        jLabel7.setText("Vokabeln");
        pnlVokabeln.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebarLernen.add(pnlVokabeln, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        pnlKana.setBackground(new java.awt.Color(55, 43, 135));
        pnlKana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKanaMouseExited(evt);
            }
        });
        pnlKana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 243, 228));
        jLabel8.setText("Kana");
        pnlKana.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebarLernen.add(pnlKana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        pnlKanji.setBackground(new java.awt.Color(55, 43, 135));
        pnlKanji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKanjiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKanjiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKanjiMouseExited(evt);
            }
        });
        pnlKanji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 243, 228));
        jLabel6.setText("Kanji");
        pnlKanji.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebarLernen.add(pnlKanji, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        pnlSidebar.add(pnlSidebarLernen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        pnlSidebarKatalog.setBackground(new java.awt.Color(55, 28, 115));
        pnlSidebarKatalog.setEnabled(false);
        pnlSidebarKatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSidebarKatalogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSidebarKatalogMouseExited(evt);
            }
        });
        pnlSidebarKatalog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 243, 228));
        jLabel1.setText("Katalog");
        pnlSidebarKatalog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlHinzufuegen.setBackground(new java.awt.Color(55, 43, 135));
        pnlHinzufuegen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHinzufuegenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHinzufuegenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHinzufuegenMouseExited(evt);
            }
        });
        pnlHinzufuegen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(223, 243, 228));
        jLabel4.setText("Hinzufügen");
        pnlHinzufuegen.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebarKatalog.add(pnlHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        pnlBearbeiten.setBackground(new java.awt.Color(55, 43, 135));
        pnlBearbeiten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBearbeitenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBearbeitenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBearbeitenMouseExited(evt);
            }
        });
        pnlBearbeiten.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(223, 243, 228));
        jLabel11.setText("Bearbeiten");
        pnlBearbeiten.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        pnlSidebarKatalog.add(pnlBearbeiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        pnlSidebar.add(pnlSidebarKatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        pnlSidebarEinstellungen.setBackground(new java.awt.Color(55, 28, 115));
        pnlSidebarEinstellungen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSidebarEinstellungenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSidebarEinstellungenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSidebarEinstellungenMouseExited(evt);
            }
        });
        pnlSidebarEinstellungen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(223, 243, 228));
        jLabel9.setText("Einstellungen");
        pnlSidebarEinstellungen.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 50));

        pnlSidebar.add(pnlSidebarEinstellungen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 160, 50));

        pnlSidebarVerlassen.setBackground(new java.awt.Color(55, 28, 115));
        pnlSidebarVerlassen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSidebarVerlassenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSidebarVerlassenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSidebarVerlassenMouseExited(evt);
            }
        });
        pnlSidebarVerlassen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 243, 228));
        jLabel5.setText("Verlassen");
        pnlSidebarVerlassen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 50));

        pnlSidebar.add(pnlSidebarVerlassen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 160, 50));

        pnlMain.add(pnlSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 1080));

        pnlContent.setBackground(new java.awt.Color(55, 28, 115));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlContentUebersicht.setBackground(new java.awt.Color(55, 28, 115));
        pnlContentUebersicht.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(187, 187, 187));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(223, 243, 228));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Übersicht");
        pnlContentUebersicht.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, -1));

        jSeparator6.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentUebersicht.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 530, 10));

        jLabel19.setBackground(new java.awt.Color(187, 187, 187));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(223, 243, 228));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("davon Sehr gut");
        pnlContentUebersicht.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 310, 30));

        txfUebersichtSehrGut.setEditable(false);
        txfUebersichtSehrGut.setBackground(new java.awt.Color(46, 23, 96));
        txfUebersichtSehrGut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfUebersichtSehrGut.setForeground(new java.awt.Color(223, 243, 228));
        txfUebersichtSehrGut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUebersichtSehrGut.setText("Test Test");
        txfUebersichtSehrGut.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfUebersichtSehrGut.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentUebersicht.add(txfUebersichtSehrGut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 250, 30));

        jSeparator7.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentUebersicht.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 580, 10));

        jSeparator8.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentUebersicht.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 530, 10));

        jSeparator9.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentUebersicht.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 530, 10));

        jLabel20.setBackground(new java.awt.Color(187, 187, 187));
        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(223, 243, 228));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Anzahl hinzugefügter Wörter:");
        pnlContentUebersicht.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 330, 30));

        txfUebersichtAnzahlWoerter.setEditable(false);
        txfUebersichtAnzahlWoerter.setBackground(new java.awt.Color(46, 23, 96));
        txfUebersichtAnzahlWoerter.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfUebersichtAnzahlWoerter.setForeground(new java.awt.Color(223, 243, 228));
        txfUebersichtAnzahlWoerter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUebersichtAnzahlWoerter.setText("Test Test");
        txfUebersichtAnzahlWoerter.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfUebersichtAnzahlWoerter.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentUebersicht.add(txfUebersichtAnzahlWoerter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 250, 30));

        jLabel21.setBackground(new java.awt.Color(187, 187, 187));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(223, 243, 228));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("davon gut");
        pnlContentUebersicht.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 310, 30));

        txfUebersichtGut.setEditable(false);
        txfUebersichtGut.setBackground(new java.awt.Color(46, 23, 96));
        txfUebersichtGut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfUebersichtGut.setForeground(new java.awt.Color(223, 243, 228));
        txfUebersichtGut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUebersichtGut.setText("Test Test");
        txfUebersichtGut.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfUebersichtGut.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentUebersicht.add(txfUebersichtGut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 250, 30));

        txfUebersichtSchlecht.setEditable(false);
        txfUebersichtSchlecht.setBackground(new java.awt.Color(46, 23, 96));
        txfUebersichtSchlecht.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfUebersichtSchlecht.setForeground(new java.awt.Color(223, 243, 228));
        txfUebersichtSchlecht.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUebersichtSchlecht.setText("Test Test");
        txfUebersichtSchlecht.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfUebersichtSchlecht.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentUebersicht.add(txfUebersichtSchlecht, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 250, 30));

        jLabel22.setBackground(new java.awt.Color(187, 187, 187));
        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(223, 243, 228));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("davon unbeantwortet / schlecht");
        pnlContentUebersicht.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 360, 30));

        pnlContent.add(pnlContentUebersicht, "card3");

        pnlContentStart.setBackground(new java.awt.Color(55, 28, 115));
        pnlContentStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfStartUser.setBackground(new java.awt.Color(46, 23, 96));
        txfStartUser.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfStartUser.setForeground(new java.awt.Color(223, 243, 228));
        txfStartUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfStartUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfStartUser.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentStart.add(txfStartUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 360, 40));

        jLabel26.setBackground(new java.awt.Color(187, 187, 187));
        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(223, 243, 228));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Start");
        pnlContentStart.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, -1));

        jSeparator14.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentStart.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 580, 10));

        jSeparator15.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentStart.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 580, 10));

        jLabel27.setBackground(new java.awt.Color(187, 187, 187));
        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(223, 243, 228));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Anmeldung");
        pnlContentStart.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 330, 30));

        jSeparator16.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentStart.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 590, 10));

        jLabel28.setBackground(new java.awt.Color(187, 187, 187));
        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(223, 243, 228));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("User:");
        pnlContentStart.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, 40));

        jLabel29.setBackground(new java.awt.Color(187, 187, 187));
        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(223, 243, 228));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Passwort:");
        pnlContentStart.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, 40));

        pnlStartAnmelden.setBackground(new java.awt.Color(55, 43, 135));
        pnlStartAnmelden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlStartAnmeldenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlStartAnmeldenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlStartAnmeldenMouseExited(evt);
            }
        });
        pnlStartAnmelden.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(223, 243, 228));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Anmelden");
        pnlStartAnmelden.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 520, 30));

        pnlContentStart.add(pnlStartAnmelden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 540, 40));

        jPasswordField1.setBackground(new java.awt.Color(46, 23, 96));
        jPasswordField1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(223, 243, 228));
        jPasswordField1.setBorder(null);
        pnlContentStart.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 360, 40));

        pnlContent.add(pnlContentStart, "card9");

        pnlContentVokabeln.setBackground(new java.awt.Color(55, 28, 115));
        pnlContentVokabeln.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 23, 96));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnlContentVokabeln.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 860, 360));

        pnlContent.add(pnlContentVokabeln, "card6");

        pnlContentKana.setBackground(new java.awt.Color(55, 28, 115));
        pnlContentKana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(223, 243, 228));
        jLabel23.setText("Richtig:");
        pnlContentKana.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(223, 243, 228));
        jSeparator11.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentKana.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 20));

        jSeparator12.setBackground(new java.awt.Color(223, 243, 228));
        jSeparator12.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentKana.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 20));

        jSeparator13.setBackground(new java.awt.Color(223, 243, 228));
        jSeparator13.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentKana.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 20));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(223, 243, 228));
        jLabel24.setText("Falsch:");
        pnlContentKana.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txfKanaContentPunkteFalsch.setEditable(false);
        txfKanaContentPunkteFalsch.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentPunkteFalsch.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        txfKanaContentPunkteFalsch.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentPunkteFalsch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentPunkteFalsch.setText("0");
        txfKanaContentPunkteFalsch.setBorder(null);
        pnlContentKana.add(txfKanaContentPunkteFalsch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 60, 60));

        txfKanaContentPunkteRichtig.setEditable(false);
        txfKanaContentPunkteRichtig.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentPunkteRichtig.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        txfKanaContentPunkteRichtig.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentPunkteRichtig.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentPunkteRichtig.setText("0");
        txfKanaContentPunkteRichtig.setBorder(null);
        pnlContentKana.add(txfKanaContentPunkteRichtig, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 252, 60, 60));

        pnlKanaContent.setBackground(new java.awt.Color(46, 23, 96));
        pnlKanaContent.setLayout(new java.awt.CardLayout());

        pnlKanaContentSeite1.setBackground(new java.awt.Color(46, 23, 96));
        pnlKanaContentSeite1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btng1.add(ckbxKanaContentSeite1btn3);
        ckbxKanaContentSeite1btn3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ckbxKanaContentSeite1btn3.setForeground(new java.awt.Color(223, 243, 228));
        ckbxKanaContentSeite1btn3.setText("Hiragana / Katakana");
        pnlKanaContentSeite1.add(ckbxKanaContentSeite1btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 40));

        ckbxKanaContentSeite1btn5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ckbxKanaContentSeite1btn5.setForeground(new java.awt.Color(223, 243, 228));
        ckbxKanaContentSeite1btn5.setText("Stimmhaft");
        pnlKanaContentSeite1.add(ckbxKanaContentSeite1btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 150, 40));

        btng1.add(ckbxKanaContentSeite1btn2);
        ckbxKanaContentSeite1btn2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ckbxKanaContentSeite1btn2.setForeground(new java.awt.Color(223, 243, 228));
        ckbxKanaContentSeite1btn2.setText("Katakana");
        pnlKanaContentSeite1.add(ckbxKanaContentSeite1btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 40));

        jSeparator10.setBackground(new java.awt.Color(223, 243, 228));
        jSeparator10.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlKanaContentSeite1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 30, 150));

        btng1.add(ckbxKanaContentSeite1btn1);
        ckbxKanaContentSeite1btn1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ckbxKanaContentSeite1btn1.setForeground(new java.awt.Color(223, 243, 228));
        ckbxKanaContentSeite1btn1.setSelected(true);
        ckbxKanaContentSeite1btn1.setText("Hiragana");
        pnlKanaContentSeite1.add(ckbxKanaContentSeite1btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 40));

        ckbxKanaContentSeite1btn4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ckbxKanaContentSeite1btn4.setForeground(new java.awt.Color(223, 243, 228));
        ckbxKanaContentSeite1btn4.setText("Gebrochen");
        pnlKanaContentSeite1.add(ckbxKanaContentSeite1btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, 40));

        pnlKanaContentSeite1Start.setBackground(new java.awt.Color(55, 28, 115));
        pnlKanaContentSeite1Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKanaContentSeite1StartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKanaContentSeite1StartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKanaContentSeite1StartMouseExited(evt);
            }
        });
        pnlKanaContentSeite1Start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(223, 243, 228));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Start");
        pnlKanaContentSeite1Start.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 330, 40));

        pnlKanaContentSeite1.add(pnlKanaContentSeite1Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 330, 50));

        pnlKanaContent.add(pnlKanaContentSeite1, "card2");

        pnlKanaContentSeite2.setBackground(new java.awt.Color(46, 23, 96));
        pnlKanaContentSeite2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfKanaContentSeite2Vorgabe.setEditable(false);
        txfKanaContentSeite2Vorgabe.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite2Vorgabe.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite2Vorgabe.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite2Vorgabe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite2Vorgabe.setText("ka");
        txfKanaContentSeite2Vorgabe.setBorder(null);
        pnlKanaContentSeite2.add(txfKanaContentSeite2Vorgabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 130, 70));

        txfKanaContentSeite2Antwort1.setEditable(false);
        txfKanaContentSeite2Antwort1.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite2Antwort1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite2Antwort1.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite2Antwort1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite2Antwort1.setText("x");
        txfKanaContentSeite2Antwort1.setBorder(null);
        txfKanaContentSeite2Antwort1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort1MouseExited(evt);
            }
        });
        pnlKanaContentSeite2.add(txfKanaContentSeite2Antwort1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 70));

        txfKanaContentSeite2Antwort2.setEditable(false);
        txfKanaContentSeite2Antwort2.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite2Antwort2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite2Antwort2.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite2Antwort2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite2Antwort2.setText("x");
        txfKanaContentSeite2Antwort2.setBorder(null);
        txfKanaContentSeite2Antwort2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort2MouseExited(evt);
            }
        });
        pnlKanaContentSeite2.add(txfKanaContentSeite2Antwort2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 130, 70));

        txfKanaContentSeite2Antwort3.setEditable(false);
        txfKanaContentSeite2Antwort3.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite2Antwort3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite2Antwort3.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite2Antwort3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite2Antwort3.setText("x");
        txfKanaContentSeite2Antwort3.setBorder(null);
        txfKanaContentSeite2Antwort3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txfKanaContentSeite2Antwort3MouseExited(evt);
            }
        });
        pnlKanaContentSeite2.add(txfKanaContentSeite2Antwort3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 130, 70));

        pnlKanaContent.add(pnlKanaContentSeite2, "card3");

        pnlKanaContentSeite3.setBackground(new java.awt.Color(46, 23, 96));
        pnlKanaContentSeite3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfKanaContentSeite3Vorgabe.setEditable(false);
        txfKanaContentSeite3Vorgabe.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite3Vorgabe.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite3Vorgabe.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite3Vorgabe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite3Vorgabe.setText("ka");
        txfKanaContentSeite3Vorgabe.setBorder(null);
        pnlKanaContentSeite3.add(txfKanaContentSeite3Vorgabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 290, 70));

        txfKanaContentSeite3Antwort.setBackground(new java.awt.Color(55, 28, 115));
        txfKanaContentSeite3Antwort.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfKanaContentSeite3Antwort.setForeground(new java.awt.Color(223, 243, 228));
        txfKanaContentSeite3Antwort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfKanaContentSeite3Antwort.setBorder(null);
        txfKanaContentSeite3Antwort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfKanaContentSeite3AntwortActionPerformed(evt);
            }
        });
        pnlKanaContentSeite3.add(txfKanaContentSeite3Antwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 630, 70));

        pnlKanaContent.add(pnlKanaContentSeite3, "card4");

        pnlKanaContentSeite4.setBackground(new java.awt.Color(46, 23, 96));
        pnlKanaContentSeite4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlKanaContent.add(pnlKanaContentSeite4, "card4");

        pnlContentKana.add(pnlKanaContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 930, 340));

        pnlContent.add(pnlContentKana, "card7");

        pnlContentKanji.setBackground(new java.awt.Color(55, 28, 115));

        javax.swing.GroupLayout pnlContentKanjiLayout = new javax.swing.GroupLayout(pnlContentKanji);
        pnlContentKanji.setLayout(pnlContentKanjiLayout);
        pnlContentKanjiLayout.setHorizontalGroup(
            pnlContentKanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlContentKanjiLayout.setVerticalGroup(
            pnlContentKanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pnlContent.add(pnlContentKanji, "card8");

        pnlContentKatalog.setBackground(new java.awt.Color(55, 28, 115));

        javax.swing.GroupLayout pnlContentKatalogLayout = new javax.swing.GroupLayout(pnlContentKatalog);
        pnlContentKatalog.setLayout(pnlContentKatalogLayout);
        pnlContentKatalogLayout.setHorizontalGroup(
            pnlContentKatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlContentKatalogLayout.setVerticalGroup(
            pnlContentKatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pnlContent.add(pnlContentKatalog, "card4");

        pnlContentHinzufuegen.setBackground(new java.awt.Color(55, 28, 115));
        pnlContentHinzufuegen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfNeuesWortJ.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortJ.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortJ.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortJ.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfNeuesWortJ.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentHinzufuegen.add(txfNeuesWortJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 40));

        txfNeuesWortD.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortD.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortD.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortD.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txfNeuesWortD.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlContentHinzufuegen.add(txfNeuesWortD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, 40));

        cbxNeuesWortKat1.setBackground(new java.awt.Color(46, 23, 96));
        cbxNeuesWortKat1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        cbxNeuesWortKat1.setForeground(new java.awt.Color(223, 243, 228));
        cbxNeuesWortKat1.setMaximumRowCount(10);
        cbxNeuesWortKat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Nomen", "Adjektiv", "Verb" }));
        cbxNeuesWortKat1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxNeuesWortKat1.setFocusable(false);
        pnlContentHinzufuegen.add(cbxNeuesWortKat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 250, 40));

        cbxNeuesWortKat2.setBackground(new java.awt.Color(46, 23, 96));
        cbxNeuesWortKat2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        cbxNeuesWortKat2.setForeground(new java.awt.Color(223, 243, 228));
        cbxNeuesWortKat2.setMaximumRowCount(4);
        cbxNeuesWortKat2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hiragana", "Katakana", "Kanji", "Wort", "Zahl", " " }));
        cbxNeuesWortKat2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxNeuesWortKat2.setFocusable(false);
        pnlContentHinzufuegen.add(cbxNeuesWortKat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 250, 40));

        cbxNeuesWortKat3.setBackground(new java.awt.Color(46, 23, 96));
        cbxNeuesWortKat3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        cbxNeuesWortKat3.setForeground(new java.awt.Color(223, 243, 228));
        cbxNeuesWortKat3.setMaximumRowCount(10);
        cbxNeuesWortKat3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basics", "Kategorie 2", "Kategorie 3", "Kategorie 4", "Kategorie 5", "Kategorie 6" }));
        cbxNeuesWortKat3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxNeuesWortKat3.setFocusable(false);
        pnlContentHinzufuegen.add(cbxNeuesWortKat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 250, 40));

        jSeparator1.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlContentHinzufuegen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 580, 10));

        lblUebersetzung.setBackground(new java.awt.Color(187, 187, 187));
        lblUebersetzung.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lblUebersetzung.setForeground(new java.awt.Color(223, 243, 228));
        lblUebersetzung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUebersetzung.setText("Übersetzung");
        pnlContentHinzufuegen.add(lblUebersetzung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        jSeparator2.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentHinzufuegen.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 230, 10));

        jLabel12.setBackground(new java.awt.Color(187, 187, 187));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(223, 243, 228));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Neues Wort hinzufügen");
        pnlContentHinzufuegen.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, -1));

        jLabel13.setBackground(new java.awt.Color(187, 187, 187));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(223, 243, 228));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Japanisch");
        pnlContentHinzufuegen.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 210, 20));

        jLabel14.setBackground(new java.awt.Color(187, 187, 187));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(223, 243, 228));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Deutsch");
        pnlContentHinzufuegen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 110, 20));

        jLabel15.setBackground(new java.awt.Color(187, 187, 187));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(223, 243, 228));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Kategorien");
        pnlContentHinzufuegen.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 190, -1));

        jSeparator3.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentHinzufuegen.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 230, 10));

        jLabel17.setBackground(new java.awt.Color(187, 187, 187));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(223, 243, 228));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Wort / Zeichen");
        pnlContentHinzufuegen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, -1));

        jSeparator5.setForeground(new java.awt.Color(223, 243, 228));
        pnlContentHinzufuegen.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 10));

        pnlNeuesWortHinzufuegen.setBackground(new java.awt.Color(55, 43, 135));
        pnlNeuesWortHinzufuegen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNeuesWortHinzufuegenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNeuesWortHinzufuegenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNeuesWortHinzufuegenMouseExited(evt);
            }
        });
        pnlNeuesWortHinzufuegen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(223, 243, 228));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hinzufügen");
        pnlNeuesWortHinzufuegen.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 520, 30));

        pnlContentHinzufuegen.add(pnlNeuesWortHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 540, 40));

        pnlNeuesWortVerbformen.setBackground(new java.awt.Color(55, 43, 135));
        pnlNeuesWortVerbformen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfNeuesWortVerbform1.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform1.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nai-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform1.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 40));

        txfNeuesWortVerbform2.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform2.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Masu-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform2.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 40));

        txfNeuesWortVerbform3.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform3.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Ba-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform3.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 40));

        txfNeuesWortVerbform4.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform4.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Befehlsform", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform4.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 40));

        txfNeuesWortVerbform5.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform5.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Willensform", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform5.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 40));

        txfNeuesWortVerbform6.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform6.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Te-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform6.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 40));

        txfNeuesWortVerbform7.setBackground(new java.awt.Color(46, 23, 96));
        txfNeuesWortVerbform7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txfNeuesWortVerbform7.setForeground(new java.awt.Color(223, 243, 228));
        txfNeuesWortVerbform7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNeuesWortVerbform7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Ta-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 10), new java.awt.Color(193, 193, 193))); // NOI18N
        txfNeuesWortVerbform7.setCaretColor(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(txfNeuesWortVerbform7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, 40));

        jLabel16.setBackground(new java.awt.Color(187, 187, 187));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(223, 243, 228));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Verb-Formen");
        pnlNeuesWortVerbformen.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, -1));

        jSeparator4.setForeground(new java.awt.Color(223, 243, 228));
        pnlNeuesWortVerbformen.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 10));

        pnlContentHinzufuegen.add(pnlNeuesWortVerbformen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 290, 420));

        pnlContent.add(pnlContentHinzufuegen, "card2");

        pnlContentEinstellungen.setBackground(new java.awt.Color(55, 28, 115));

        javax.swing.GroupLayout pnlContentEinstellungenLayout = new javax.swing.GroupLayout(pnlContentEinstellungen);
        pnlContentEinstellungen.setLayout(pnlContentEinstellungenLayout);
        pnlContentEinstellungenLayout.setHorizontalGroup(
            pnlContentEinstellungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlContentEinstellungenLayout.setVerticalGroup(
            pnlContentEinstellungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pnlContent.add(pnlContentEinstellungen, "card5");

        pnlMain.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 1200, 550));

        jSeparator17.setForeground(new java.awt.Color(223, 243, 228));
        jSeparator17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlMain.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, 230, 10));

        txfMainUhr.setEditable(false);
        txfMainUhr.setBackground(new java.awt.Color(11, 15, 30));
        txfMainUhr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        txfMainUhr.setForeground(new java.awt.Color(223, 243, 228));
        txfMainUhr.setText("Uhr");
        txfMainUhr.setBorder(null);
        txfMainUhr.setFocusable(false);
        pnlMain.add(txfMainUhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 120, 260, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void pnlSidebarLernenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarLernenMouseEntered
        ausklappen1(pnlSidebarLernen);
    }//GEN-LAST:event_pnlSidebarLernenMouseEntered

    private void pnlSidebarLernenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarLernenMouseExited
    }//GEN-LAST:event_pnlSidebarLernenMouseExited

    private void pnlSidebarUebersichtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarUebersichtMouseEntered
        hover(pnlSidebarUebersicht);
    }//GEN-LAST:event_pnlSidebarUebersichtMouseEntered

    private void pnlHinzufuegenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHinzufuegenMouseEntered
        hover(pnlHinzufuegen);
    }//GEN-LAST:event_pnlHinzufuegenMouseEntered

    private void pnlSidebarKatalogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarKatalogMouseEntered
        ausklappen2(pnlSidebarKatalog);
    }//GEN-LAST:event_pnlSidebarKatalogMouseEntered

    private void pnlVokabelnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVokabelnMouseEntered
        hover(pnlVokabeln);
    }//GEN-LAST:event_pnlVokabelnMouseEntered

    private void pnlKanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaMouseEntered
        hover(pnlKana);
    }//GEN-LAST:event_pnlKanaMouseEntered

    private void pnlKanjiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanjiMouseEntered
        hover(pnlKanji);
    }//GEN-LAST:event_pnlKanjiMouseEntered

    private void pnlMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMouseEntered
        einklappen1(pnlSidebarLernen);
        einklappen2(pnlSidebarKatalog);
    }//GEN-LAST:event_pnlMainMouseEntered

    private void pnlSidebarUebersichtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarUebersichtMouseExited
        pnlSidebarUebersicht.setBackground(c2);
    }//GEN-LAST:event_pnlSidebarUebersichtMouseExited

    private void pnlHinzufuegenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHinzufuegenMouseExited
        pnlHinzufuegen.setBackground(c6);
    }//GEN-LAST:event_pnlHinzufuegenMouseExited

    private void pnlSidebarKatalogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarKatalogMouseExited
        
    }//GEN-LAST:event_pnlSidebarKatalogMouseExited

    private void pnlKanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaMouseExited
        pnlKana.setBackground(c6);
    }//GEN-LAST:event_pnlKanaMouseExited

    private void pnlVokabelnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVokabelnMouseExited
        pnlVokabeln.setBackground(c6);
    }//GEN-LAST:event_pnlVokabelnMouseExited

    private void pnlKanjiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanjiMouseExited
        pnlKanji.setBackground(c6);
    }//GEN-LAST:event_pnlKanjiMouseExited

    private void pnlSidebarVerlassenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarVerlassenMouseEntered
        hover(pnlSidebarVerlassen);
    }//GEN-LAST:event_pnlSidebarVerlassenMouseEntered

    private void pnlSidebarVerlassenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarVerlassenMouseExited
        pnlSidebarVerlassen.setBackground(c6);
    }//GEN-LAST:event_pnlSidebarVerlassenMouseExited

    private void pnlSidebarEinstellungenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarEinstellungenMouseEntered
        hover(pnlSidebarEinstellungen);
    }//GEN-LAST:event_pnlSidebarEinstellungenMouseEntered

    private void pnlSidebarEinstellungenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarEinstellungenMouseExited
        pnlSidebarEinstellungen.setBackground(c6);
    }//GEN-LAST:event_pnlSidebarEinstellungenMouseExited

    private void pnlSidebarUebersichtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarUebersichtMouseClicked
        try {
            updateUebersicht();
        } catch (Exception ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        showContent(pnlContent, pnlContentUebersicht);
    }//GEN-LAST:event_pnlSidebarUebersichtMouseClicked

    private void pnlHinzufuegenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHinzufuegenMouseClicked
        showContent(pnlContent, pnlContentHinzufuegen);
    }//GEN-LAST:event_pnlHinzufuegenMouseClicked

    private void pnlVokabelnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVokabelnMouseClicked
        showContent(pnlContent, pnlContentVokabeln);
    }//GEN-LAST:event_pnlVokabelnMouseClicked

    private void pnlKanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaMouseClicked
        punkte_Richtig = 0; punkte_Falsch = 0; kana_Streak_Counter = 0;
        setPunkte();
        showContent(pnlKanaContent, pnlKanaContentSeite1);
        showContent(pnlContent, pnlContentKana);
    }//GEN-LAST:event_pnlKanaMouseClicked

    private void pnlKanjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanjiMouseClicked
        showContent(pnlContent, pnlContentKanji);
    }//GEN-LAST:event_pnlKanjiMouseClicked

    private void pnlSidebarEinstellungenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarEinstellungenMouseClicked
        showContent(pnlContent, pnlContentEinstellungen);
    }//GEN-LAST:event_pnlSidebarEinstellungenMouseClicked

    private void pnlBearbeitenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBearbeitenMouseClicked
        //
    }//GEN-LAST:event_pnlBearbeitenMouseClicked

    private void pnlBearbeitenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBearbeitenMouseEntered
        hover(pnlBearbeiten);
    }//GEN-LAST:event_pnlBearbeitenMouseEntered

    private void pnlBearbeitenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBearbeitenMouseExited
        pnlBearbeiten.setBackground(c6);
    }//GEN-LAST:event_pnlBearbeitenMouseExited

    private void pnlNeuesWortHinzufuegenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNeuesWortHinzufuegenMouseEntered
        hover(pnlNeuesWortHinzufuegen);
    }//GEN-LAST:event_pnlNeuesWortHinzufuegenMouseEntered

    private void pnlNeuesWortHinzufuegenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNeuesWortHinzufuegenMouseExited
        pnlNeuesWortHinzufuegen.setBackground(c6);
    }//GEN-LAST:event_pnlNeuesWortHinzufuegenMouseExited

    private void pnlNeuesWortHinzufuegenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNeuesWortHinzufuegenMouseClicked
        try{
        if(cbxNeuesWortKat1.getSelectedIndex() == 3){
            dm.addVokabel(new Verb(txfNeuesWortD.getText(), txfNeuesWortJ.getText(), txfNeuesWortVerbform1.getText(), txfNeuesWortVerbform2.getText(), txfNeuesWortVerbform3.getText(), txfNeuesWortVerbform4.getText(), txfNeuesWortVerbform5.getText(), txfNeuesWortVerbform6.getText(), txfNeuesWortVerbform7.getText(), cbxNeuesWortKat1.getItemAt(cbxNeuesWortKat1.getSelectedIndex()), cbxNeuesWortKat2.getItemAt(cbxNeuesWortKat2.getSelectedIndex()), cbxNeuesWortKat3.getItemAt(cbxNeuesWortKat3.getSelectedIndex())));
        }
        else {
            dm.addVokabel(new Vokabel(txfNeuesWortJ.getText(), txfNeuesWortD.getText(), cbxNeuesWortKat1.getItemAt(cbxNeuesWortKat1.getSelectedIndex()), cbxNeuesWortKat2.getItemAt(cbxNeuesWortKat2.getSelectedIndex()), cbxNeuesWortKat3.getItemAt(cbxNeuesWortKat3.getSelectedIndex())));
        }
        } catch(Exception e){
            System.out.println(e);
        }
        txfNeuesWortD.setText("");
        txfNeuesWortJ.setText("");
        cbxNeuesWortKat1.setSelectedIndex(0);
        cbxNeuesWortKat2.setSelectedIndex(0);
        cbxNeuesWortKat3.setSelectedIndex(0);
        txfNeuesWortVerbform1.setText("");
        txfNeuesWortVerbform2.setText("");
        txfNeuesWortVerbform3.setText("");
        txfNeuesWortVerbform4.setText("");
        txfNeuesWortVerbform5.setText("");
        txfNeuesWortVerbform6.setText("");
        txfNeuesWortVerbform7.setText("");
    }//GEN-LAST:event_pnlNeuesWortHinzufuegenMouseClicked

    private void pnlSidebarVerlassenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSidebarVerlassenMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlSidebarVerlassenMouseClicked

    private void pnlKanaContentSeite1StartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaContentSeite1StartMouseClicked
        punkte_Richtig = 0;
        punkte_Falsch = 0;
        int idContent = 0;
        
        if(ckbxKanaContentSeite1btn1.isSelected() && ckbxKanaContentSeite1btn4.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 13;}
        else if(ckbxKanaContentSeite1btn1.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 12;}
        else if(ckbxKanaContentSeite1btn1.isSelected() && ckbxKanaContentSeite1btn4.isSelected()){idContent = 11;}
        else if(ckbxKanaContentSeite1btn1.isSelected()){idContent = 10;}
        
        else if(ckbxKanaContentSeite1btn2.isSelected() && ckbxKanaContentSeite1btn4.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 23;}
        else if(ckbxKanaContentSeite1btn2.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 22;}
        else if(ckbxKanaContentSeite1btn2.isSelected() && ckbxKanaContentSeite1btn4.isSelected()){idContent = 21;}
        else if(ckbxKanaContentSeite1btn2.isSelected()){idContent = 20;}
        
        else if(ckbxKanaContentSeite1btn3.isSelected() && ckbxKanaContentSeite1btn4.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 33;}
        else if(ckbxKanaContentSeite1btn3.isSelected() && ckbxKanaContentSeite1btn5.isSelected()){idContent = 32;}
        else if(ckbxKanaContentSeite1btn3.isSelected() && ckbxKanaContentSeite1btn4.isSelected()){idContent = 31;}
        else if(ckbxKanaContentSeite1btn3.isSelected()){idContent = 30;}
        
        dm.setContent(0, idContent);
        setKanaContentSeite2(0);
    }//GEN-LAST:event_pnlKanaContentSeite1StartMouseClicked

    private void pnlKanaContentSeite1StartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaContentSeite1StartMouseEntered
        hover(pnlKanaContentSeite1Start);
    }//GEN-LAST:event_pnlKanaContentSeite1StartMouseEntered

    private void pnlKanaContentSeite1StartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKanaContentSeite1StartMouseExited
        pnlKanaContentSeite1Start.setBackground(c6);
    }//GEN-LAST:event_pnlKanaContentSeite1StartMouseExited

    private void txfKanaContentSeite2Antwort1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort1MouseEntered
        hover(txfKanaContentSeite2Antwort1);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort1MouseEntered

    private void txfKanaContentSeite2Antwort1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort1MouseExited
        txfKanaContentSeite2Antwort1.setBackground(c7);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort1MouseExited

    private void txfKanaContentSeite2Antwort2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort2MouseEntered
        hover(txfKanaContentSeite2Antwort2);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort2MouseEntered

    private void txfKanaContentSeite2Antwort2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort2MouseExited
        txfKanaContentSeite2Antwort2.setBackground(c7);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort2MouseExited

    private void txfKanaContentSeite2Antwort3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort3MouseEntered
        hover(txfKanaContentSeite2Antwort3);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort3MouseEntered

    private void txfKanaContentSeite2Antwort3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort3MouseExited
        txfKanaContentSeite2Antwort3.setBackground(c7);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort3MouseExited

    private void txfKanaContentSeite2Antwort1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort1MouseClicked
        checkKanaContentSeite2(1);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort1MouseClicked

    private void txfKanaContentSeite2Antwort2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort2MouseClicked
        checkKanaContentSeite2(2);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort2MouseClicked

    private void txfKanaContentSeite2Antwort3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfKanaContentSeite2Antwort3MouseClicked
        checkKanaContentSeite2(3);
    }//GEN-LAST:event_txfKanaContentSeite2Antwort3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void pnlStartAnmeldenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStartAnmeldenMouseClicked
        //Daten einlesen
        
        showContent(pnlContent, pnlContentUebersicht);
    }//GEN-LAST:event_pnlStartAnmeldenMouseClicked

    private void pnlStartAnmeldenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStartAnmeldenMouseEntered
        hover(pnlStartAnmelden);
    }//GEN-LAST:event_pnlStartAnmeldenMouseEntered

    private void pnlStartAnmeldenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStartAnmeldenMouseExited
        pnlStartAnmelden.setBackground(c6);
    }//GEN-LAST:event_pnlStartAnmeldenMouseExited

    private void txfKanaContentSeite3AntwortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfKanaContentSeite3AntwortActionPerformed
        checkKanaContentSeite3();
    }//GEN-LAST:event_txfKanaContentSeite3AntwortActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainInterface().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
        
    }

    private int id_Antwort, punkte_Richtig, punkte_Falsch, kana_Streak_Counter;
    private String kana_P3_Antwort;
    boolean r_to_k = false;
    int x = 50;
    int y = 50;
    Color c1 = new Color(23,23,56);
    Color c2 = new Color(46,23,96);
    Color c3 = new Color(230,175,46);
    Color c4 = new Color(113,128,185);
    Color c5 = new Color(223, 243, 228);
    Color c6 = new Color(55,43,135);
    Color c7 = new Color(55,28,115);

    private DataManager dm = new DataManager();
    private MySQLAccess msa = new MySQLAccess();
    private LearningManager lmn = new LearningManager();
    
    private void updateUebersicht() throws Exception{
        dm.laodDBData();
        ArrayList<Vokabel> vocs = dm.getDataVocs();
        
        for(int x = 0; x < 3; x++){
            int counter = 0;
            for(int y = 0; y < vocs.size(); y++){
                switch(x){
                    case 0:
                        if(vocs.get(y).getStreak() >= 4){counter++;}
                        break;
                    case 1:
                        if(vocs.get(y).getStreak() >= 2 && vocs.get(y).getStreak() < 4){counter++;}
                        break;
                    case 2:
                        if(vocs.get(y).getStreak() < 2){counter++;}
                        break;
                }
            }
            
            switch(x){
                case 0:
                    txfUebersichtSehrGut.setText(Integer.toString(counter));
                   break; 
                case 1:
                    txfUebersichtGut.setText(Integer.toString(counter));
                    break;
                case 2:
                    txfUebersichtSchlecht.setText(Integer.toString(counter));
                    break;
            }
        }
        txfUebersichtAnzahlWoerter.setText(Integer.toString(vocs.size()));
    }
    
    public void initUhr(){
                
        Thread th = new Thread() {
            @Override
            public void run(){
                while(true){
                    try {
                        LocalTime myTime = LocalTime.now();
                        DateTimeFormatter myFormat = DateTimeFormatter.ofPattern("HH:mm:ss");
                        String formattedTime = myTime.format(myFormat);
                        txfMainUhr.setText(formattedTime);
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; th.start();
    }
    
    private void showContent(JPanel pnlParent, JPanel pnl2){
        pnlParent.removeAll();
        pnlParent.add(pnl2);
        pnlParent.repaint();
        pnlParent.revalidate();
    }
    
    private void hover(JPanel pnl){
        pnl.setBackground(c3);
    }
    private void hover(JTextField txf){
        txf.setBackground(c3);
    }
    
    private void ausklappen1(JPanel pnl){
        if (x == 50){
            pnl.setSize(200, 50);
            pnlSidebarKatalog.setLocation(0, 200);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for(int i = 51; i <= 200; i++){
                            Thread.sleep(1);
                            pnl.setSize(200, i);
                            pnlSidebarKatalog.setLocation(0, pnlSidebarKatalog.getY() + 1);
                        }
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    pnlSidebarKatalog.setLocation(0, 350);
                }
            }; th.start();
            x = 200;
        }
    }
   
    private void einklappen1(JPanel pnl) {
        if (x == 200){
            pnl.setSize(200, 200);
            pnlSidebarKatalog.setLocation(0, 350);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for(int i = 199; i >= 50; i--){
                            Thread.sleep(1);
                            pnl.setSize(200, i);
                            pnlSidebarKatalog.setLocation(0, pnlSidebarKatalog.getY() - 1);
                        }
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    pnlSidebarKatalog.setLocation(0, 200);
                }
            }; th.start();
            x = 50;
        }
    }
    
    private void ausklappen2(JPanel pnl){
        if (y == 50){
            pnl.setSize(200, 50);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for(int i = 51; i <= 150; i++){
                            Thread.sleep(1);
                            pnl.setSize(200, i);
                        }
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            y = 150;
        }
    }
   
    private void einklappen2(JPanel pnl) {
        if (y == 150){
            pnl.setSize(200, 150);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for(int i = 149; i >= 50; i--){
                            Thread.sleep(1);
                            pnl.setSize(200, i);
                        }
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            y = 50;
        }
    }
    
    public void checkKanaContentSeite2(int id){

                if(id == id_Antwort){
                    punkte_Richtig++;
                    kana_Streak_Counter++;
                    setPunkte();
                }
                else{
                    punkte_Falsch++;
                    setPunkte();
                }
                setKanaContentSeite2(1);
    }
    
    /*
        id => determines if Content is set on Start or after previous run
                0 -> on start
                1-> after answere
    */
    
    public void setKanaContentSeite2(int id){
        
        String[] content;
        
        if(kana_Streak_Counter >= 10){
            if(!r_to_k){r_to_k = true;}
            else {r_to_k = false;}
            kana_Streak_Counter = 0;
        }
        if(!r_to_k){
            content = dm.getRandomContent(01);
        } else {
            content = dm.getRandomContent(02);
        }
        
        txfKanaContentSeite2Vorgabe.setText(content[0]);
        
        Random rand = new Random();
        int rand_num = rand.nextInt(3);
        switch(rand_num){
            case 0:
                txfKanaContentSeite2Antwort1.setText(content[1]);
                txfKanaContentSeite2Antwort2.setText(content[2]);
                txfKanaContentSeite2Antwort3.setText(content[3]);
                id_Antwort = 1;
                break;
            
            case 1:
                txfKanaContentSeite2Antwort1.setText(content[3]);
                txfKanaContentSeite2Antwort2.setText(content[1]);
                txfKanaContentSeite2Antwort3.setText(content[2]);
                id_Antwort = 2;
                break;
            
            case 2:
                txfKanaContentSeite2Antwort1.setText(content[2]);
                txfKanaContentSeite2Antwort2.setText(content[3]);
                txfKanaContentSeite2Antwort3.setText(content[1]);
                id_Antwort = 3;
                break;
            
        }
        
        switch(id){
            case 0: 
                showContent(pnlKanaContent, pnlKanaContentSeite2);
                break;
            
            case 1: 
                if(punkte_Richtig*2 > punkte_Falsch && punkte_Richtig > 19){
                    setKanaContentSeite3(0);
                    showContent(pnlKanaContent, pnlKanaContentSeite3);
                    
                }
        }
    }
    
    public void checkKanaContentSeite3(){
        
        if(txfKanaContentSeite3Antwort.getText().equals(kana_P3_Antwort)){
                    punkte_Richtig++;
                    setPunkte();
                }
                else{
                    punkte_Falsch++;
                    setPunkte();
                }
                setKanaContentSeite3(1);
    }
    
    public void setKanaContentSeite3(int id) {
        
        String[] content = dm.getRandomContent(03);
        
        txfKanaContentSeite3Antwort.setText("");
        txfKanaContentSeite3Antwort.requestFocus();
        txfKanaContentSeite3Vorgabe.setText(content[0]);
        kana_P3_Antwort = content[1];
        
        
        switch(id){
            case 0: 
                showContent(pnlKanaContent, pnlKanaContentSeite3);
                break;
            case 1: 
                if(punkte_Richtig*1.5 > punkte_Falsch && punkte_Richtig > 39){
                    showContent(pnlKanaContent, pnlKanaContentSeite1);
                }
        }
    }
    
    public void setPunkte(){
        txfKanaContentPunkteRichtig.setText(Integer.toString(punkte_Richtig));
        txfKanaContentPunkteFalsch.setText(Integer.toString(punkte_Falsch));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btng1;
    private javax.swing.JComboBox<String> cbxNeuesWortKat1;
    private javax.swing.JComboBox<String> cbxNeuesWortKat2;
    private javax.swing.JComboBox<String> cbxNeuesWortKat3;
    private javax.swing.JCheckBox ckbxKanaContentSeite1btn1;
    private javax.swing.JCheckBox ckbxKanaContentSeite1btn2;
    private javax.swing.JCheckBox ckbxKanaContentSeite1btn3;
    private javax.swing.JCheckBox ckbxKanaContentSeite1btn4;
    private javax.swing.JCheckBox ckbxKanaContentSeite1btn5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblUebersetzung;
    private javax.swing.JPanel pnlBearbeiten;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlContentEinstellungen;
    private javax.swing.JPanel pnlContentHinzufuegen;
    private javax.swing.JPanel pnlContentKana;
    private javax.swing.JPanel pnlContentKanji;
    private javax.swing.JPanel pnlContentKatalog;
    private javax.swing.JPanel pnlContentStart;
    private javax.swing.JPanel pnlContentUebersicht;
    private javax.swing.JPanel pnlContentVokabeln;
    private javax.swing.JPanel pnlHinzufuegen;
    private javax.swing.JPanel pnlKana;
    private javax.swing.JPanel pnlKanaContent;
    private javax.swing.JPanel pnlKanaContentSeite1;
    private javax.swing.JPanel pnlKanaContentSeite1Start;
    private javax.swing.JPanel pnlKanaContentSeite2;
    private javax.swing.JPanel pnlKanaContentSeite3;
    private javax.swing.JPanel pnlKanaContentSeite4;
    private javax.swing.JPanel pnlKanji;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNeuesWortHinzufuegen;
    private javax.swing.JPanel pnlNeuesWortVerbformen;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlSidebarEinstellungen;
    private javax.swing.JPanel pnlSidebarKatalog;
    private javax.swing.JPanel pnlSidebarLernen;
    private javax.swing.JPanel pnlSidebarUebersicht;
    private javax.swing.JPanel pnlSidebarVerlassen;
    private javax.swing.JPanel pnlStartAnmelden;
    private javax.swing.JPanel pnlVokabeln;
    private javax.swing.JTextField txfKanaContentPunkteFalsch;
    private javax.swing.JTextField txfKanaContentPunkteRichtig;
    private javax.swing.JTextField txfKanaContentSeite2Antwort1;
    private javax.swing.JTextField txfKanaContentSeite2Antwort2;
    private javax.swing.JTextField txfKanaContentSeite2Antwort3;
    private javax.swing.JTextField txfKanaContentSeite2Vorgabe;
    private javax.swing.JTextField txfKanaContentSeite3Antwort;
    private javax.swing.JTextField txfKanaContentSeite3Vorgabe;
    private javax.swing.JTextField txfMainUhr;
    private javax.swing.JTextField txfNeuesWortD;
    private javax.swing.JTextField txfNeuesWortJ;
    private javax.swing.JTextField txfNeuesWortVerbform1;
    private javax.swing.JTextField txfNeuesWortVerbform2;
    private javax.swing.JTextField txfNeuesWortVerbform3;
    private javax.swing.JTextField txfNeuesWortVerbform4;
    private javax.swing.JTextField txfNeuesWortVerbform5;
    private javax.swing.JTextField txfNeuesWortVerbform6;
    private javax.swing.JTextField txfNeuesWortVerbform7;
    private javax.swing.JTextField txfStartUser;
    private javax.swing.JTextField txfUebersichtAnzahlWoerter;
    private javax.swing.JTextField txfUebersichtGut;
    private javax.swing.JTextField txfUebersichtSchlecht;
    private javax.swing.JTextField txfUebersichtSehrGut;
    // End of variables declaration//GEN-END:variables
}

